name: epimetheus_nullable
description: Nullable epimetheus code.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Language
  pedantic: ^1.9.2
  async: ^2.4.2

  # Main app code
  epimetheus:
    path: '../..'

  # APIs
  iapetus:
    path: '../iapetus'
  proxies:
    git:
      url: 'https://github.com/hacker1024/proxies'
      ref: '8aa79d18e5cf9548d83a985a885a1ae6937f75ad'

  # State
  mobx: ^1.2.1+4

  # Storage
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  # Logging
  logger: ^0.9.4

  # Audio service
  audio_service:
    git:
      url: 'https://github.com/ryanheise/audio_service'
      ref: '47e6a88dfce9ac3ab226e124f717d1484da3ed0e'

dev_dependencies:
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2
