name: epimetheus
description: The open-source Pandora Music client for Android.

version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  http: ^0.12.0+1
  connectivity: ^0.4.2
  flutter_secure_storage: ^3.2.0
  audio_service:
    path: './audio_service'
  qudio:
    path: './qudio'
  palette_generator: ^0.1.1
  paging:
    path: './paging'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/music_note.png
