name: epimetheus
description: The Epimethus app - an open source Pandora client for Android, with other platforms coming soon™.

version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  dio: 3.0.10
  http: ^0.12.0+2 # TODO remove HTTP usage entirely; use Dio everywhere
  connectivity: ^0.4.5+3
  flutter_secure_storage: ^3.3.3
  audio_service:
    git:
      url: git://github.com/ryanheise/audio_service.git
  just_audio: ^0.4.1
#    path: './just_audio'
  palette_generator: ^0.2.3
  flare_flutter: ^2.0.6
  flutter_pagewise: ^1.2.3
  flutter_pagination_wrapper:
    path: './flutter_pagination_wrapper'
  url_launcher: ^5.5.1
  transparent_image: ^1.0.0
  flutter_cache_manager: ^1.4.1
  cached_network_image: ^2.3.1
  flutter_autofill:
    path: './flutter_autofill'
  carousel_slider: ^2.2.1
  outline_material_icons: ^0.1.0
  flutter_svg: ^0.19.0
  shared_preferences: ^0.5.7
  fast_marquee:
    path: './fast_marquee'
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
