name: epimetheus
description: The Epimethus app - an open source Pandora client for Android, with other platforms coming soon™.

version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.0
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  connectivity: ^0.4.5+3
  flutter_secure_storage: ^3.3.3
#  json_annotation: ^3.0.1
  audio_service:
    git:
      url: git://github.com/ryanheise/audio_service.git
  just_audio: ^0.4.1
#    path: './just_audio'
#  audio_service:
#    path: './audio_service'
#  just_audio: ^0.0.2
#  qudio:
#    path: './qudio'
#  audio:
#    path: './flutter_audio'
  palette_generator: ^0.2.3
  flare_flutter: ^2.0.6
  flutter_pagewise: ^1.2.3
  flutter_pagination_wrapper:
    path: './flutter_pagination_wrapper'
  url_launcher: ^5.5.1
  transparent_image: ^1.0.0
  flutter_cache_manager: ^1.4.1
  cached_network_image: ^2.3.1
  flutter_autofill:
    path: './flutter_autofill'
  carousel_slider: ^2.2.1
  outline_material_icons: ^0.1.0
  flutter_svg: ^0.18.1
  shared_preferences: ^0.5.7
  fast_marquee:
    path: './fast_marquee'
  amseekbar: ^0.1.2
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
#  flutter_stetho: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ^1.10.2
#  json_serializable: ^3.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
