name: epimetheus
description: The Epimethus app - an open source Pandora client for Android, with other platforms coming soon™.

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  connectivity: ^0.4.3+7
  flutter_secure_storage: ^3.2.1+1
  audio_service: ^0.4.1
  qudio:
    path: './qudio'
  palette_generator: ^0.2.0
  flare_flutter: ^1.5.5
  flutter_pagewise: ^1.2.3
  flutter_flipperkit: ^0.0.20
  flipperkit_http_interceptor: ^0.0.1
  url_launcher: ^5.1.2
  transparent_image: ^1.0.0
  flutter_cache_manager: ^1.1.1
  cached_network_image: ^1.1.1
  flutter_autofill:
    path: './flutter_autofill'
  carousel_slider: ^1.3.0
  outline_material_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
