name: epimetheus
description: The open-source Pandora Music client for Android.

version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: any
  http: any
  connectivity: any
  flutter_secure_storage: any
  audio_service: any
  qudio:
    path: './qudio'
  palette_generator: any
  flare_flutter: any
  flutter_pagewise: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
