name: CI

# Controls when the action will run.
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v1.4.2
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - run: flutter config --no-analytics
      - run: flutter config --enable-macos-desktop
      - run: flutter config --enable-web
      - run: flutter pub get

      - run: flutter build web --release

      - run: |
          cd build/web
          git init
          git config user.name "Epimetheus CI"
          git config user.email "hacker1024@users.sourceforge.net"
          git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/EpimetheusMusicPlayer/Epimetheus.git
          git checkout -b gh-pages
          git add .
          git commit -m "Built latest web release off the dev branch"
          git push --force secure-origin gh-pages
          cd -

      - uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v2
        with:
          name: android-release.apk.zip
          path: build/app/outputs/apk/release/app-release.apk

      - run: flutter build ios --release --no-codesign

      - uses: papeloto/action-zip@v1
        with:
          files: build/ios/iphoneos/Runner.app/
          dest: build/ios/iphoneos/Runner.app.zip

      - uses: actions/upload-artifact@v2
        with:
          name: ios-release.app.zip
          path: build/ios/iphoneos/Runner.app.zip

      - run: flutter build macos --release

      - uses: papeloto/action-zip@v1
        with:
          files: build/macos/Build/Products/Release/Epimetheus.app/
          dest: build/macos/Build/Products/Release/Epimetheus.app.zip

      - uses: actions/upload-artifact@v2
        with:
          name: macos-release.app.zip
          path: build/macos/Build/Products/Release/Epimetheus.app.zip