name: CI

on:
  push:
    branches: [ dev-new-architecture ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Check out the repository.
      # https://github.com/actions/checkout/issues/116#issuecomment-573880976.
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.ACCESS_TOKEN }}:${{ secrets.ACCESS_TOKEN }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive

      # Set up Java (for the Android SDK).
      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      # Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      # Configure Flutter.
      - run: flutter config --no-analytics
      - run: flutter config --enable-macos-desktop
      - run: flutter config --enable-web

      # Download Pub packages.
      - run: flutter pub get

      # Build for Android.
      - run: flutter build apk --no-sound-null-safety --split-per-abi --release
      - run: flutter build apk --no-sound-null-safety --split-per-abi --debug

      # Build for macOS, and zip the .apps.
      - run: flutter build macos --no-sound-null-safety --release
      - run: flutter build macos --no-sound-null-safety --debug
      - uses: papeloto/action-zip@v1
        with:
          files: build/macos/Build/Products/Release/Epimetheus.app
          dest:  build/macos/Build/Products/Release/Epimetheus.app.zip
      - uses: papeloto/action-zip@v1
        with:
          files: build/macos/Build/Products/Debug/Epimetheus.app
          dest: build/macos/Build/Products/Debug/Epimetheus.app.zip

      # Push the builds to the automatic build repository.
      - name: Push builds
        run:
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/EpimetheusMusicPlayer/Epimetheus-Automatic-Builds publish
          cd publish
          git switch -c ${{ github.head_ref }}
          mkdir -p Android && rm -rf Android/*
          cp ../build/app/outputs/flutter-apk/app-*-*.apk Android/
          mkdir -p macOS && rm -rf macOS/*
          cp ../build/macos/Build/Products/*/Epimetheus.app.zip macOS/
          git commit -m "{{ github.sha }}"
          if (( $(git rev-list --count {{ github.head_ref }}) > 10 )); then git replace -f --graft HEAD~9 && git filter-branch -- --all; fi
          git push --force origin ${{ github.head_ref }}